select 
  T3.CANONICA,
  T3.FLEXIONADA,
  T3.ACCIDENTES,
  ST.SIG_CORTO, ST.SIG_LARGO
FROM
  TAUBER3 T3 INNER JOIN STRONG ST
  ON T3.CANONICA=ST.BETA
WHERE
    T3.REFERENTE_ID is null
    AND T3.TIPO_PALABRA='V-'
order by T3.CANONICA

go
select * from VERBOS where VERBO='A)NATA/SSW'
go
update TAUBER3 set REFERENTE_ID='-5ca8622f:10cac2f4003:-7fe5-5ca8' where CANONICA='A)NAGNWRI/ZOMAI'
go
select distinct
  SIG.NUMERO,
  ST.SIG_CORTO, 
  ST.SIG_LARGO,
  ST.SIG_LIDDEL
FROM
  TAUBER3 T3 INNER JOIN STRONG ST
  ON T3.CANONICA=ST.BETA
WHERE
    T3.REFERENTE_ID is null
    AND T3.TIPO_PALABRA='V-'
go
update STRONG set SIG_LIDDEL=TRIM(SIG_LIDDEL)  where SIG_LIDDEL is not null